#!/bin/sh

#branch="$(git rev-parse --abbrev-ref HEAD)"

#if [ "$branch" = "master" ]; then
  #echo "You can't commit directly to master branch"
  #exit 1
#fi


npm run test

if [ $? -ne 0 ]; then
  echo "This push has been aborted because the tests failed."
  exit 1
fi


npm run linter

if [ $? -ne 0 ]; then
  echo "This push has been aborted because the linter failed."
  exit 1
fi


sudo dpl --provider=heroku --app=monteir4-sem3 --api-key=f6fa7d11-1d70-458e-8b60-55ea7d82e90e

if [ $? -ne 0 ]; then
  echo "This push has been aborted because the deployment failed."
  exit 1
fi

exit 0