#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  echo "You can't commit directly to master branch"
  exit 1
fi


npm run test

if [ $? -ne 0 ]; then
  echo "This commit has been aborted because the tests failed."
  exit 1
fi


npm run linter

if [ $? -ne 0 ]; then
  echo "This commit has been aborted because the linter failed."
  exit 1
fi

exit 0