name: Continuous Integration - Deploy Master on Heroku

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install node packages
        run: npm install
      - name: Run linter
        run: npm run linter
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install node packages
        run: npm install
      - name: Run tests
        run: npm run test
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "f6fa7d11-1d70-458e-8b60-55ea7d82e90e"
          heroku_app_name: "monteir4-sem3"
          heroku_email: "joao_saavedra_18@hotmail.com"